'use client';

import { supabase } from '@/lib/supabaseClient';

// Provision a brand-new user's restaurant on first authenticated session.
//
// Why this is its own step (and not done inline at sign-up): this Supabase
// project has email confirmation enabled, so signUp() returns NO session. RLS
// then blocks inserting the restaurant/profile rows (no auth.uid()). So we stash
// the restaurant name in the auth user's metadata at sign-up and create the
// rows the first time the user actually has a session — either immediately
// after sign-up (if confirmation is off) or right after their first login.
//
// Idempotent: if a profile already exists, it is a no-op.
export async function ensureRestaurantProvisioned(user) {
  if (!user) return { error: 'No user' };

  // Already provisioned?
  const { data: existing, error: profSelErr } = await supabase
    .from('profiles')
    .select('id, restaurant_id, role')
    .eq('id', user.id)
    .maybeSingle();

  if (profSelErr) return { error: profSelErr.message };
  if (existing) return { profile: existing };

  const meta = user.user_metadata || {};
  const name = (meta.restaurant_name || '').trim() || 'My Restaurant';
  const city = (meta.restaurant_city || '').trim() || null;

  // We generate the restaurant id client-side and do NOT use INSERT..RETURNING.
  // Reason: the restaurants SELECT policy is `id = current_restaurant_id()`,
  // which is NULL until a profile exists — so a RETURNING read here would come
  // back empty and break the flow. Supplying the id lets us link the profile
  // without reading the row back.
  const restaurantId =
    (globalThis.crypto && globalThis.crypto.randomUUID
      ? globalThis.crypto.randomUUID()
      : null);
  if (!restaurantId) return { error: 'crypto.randomUUID unavailable' };

  // 1) Restaurant (api_key is auto-generated by the DB default).
  const { error: restErr } = await supabase
    .from('restaurants')
    .insert({ id: restaurantId, name, city });
  if (restErr) return { error: 'Creating restaurant failed: ' + restErr.message };

  // 2) Profile linking this auth user to the restaurant as manager.
  const { error: profErr } = await supabase
    .from('profiles')
    .insert({ id: user.id, restaurant_id: restaurantId, role: 'manager' });
  if (profErr) return { error: 'Creating profile failed: ' + profErr.message };

  // 3) Settings row with defaults (profile now exists, so RLS allows this).
  await supabase
    .from('settings')
    .upsert({ restaurant_id: restaurantId }, { onConflict: 'restaurant_id' });

  return {
    profile: { id: user.id, restaurant_id: restaurantId, role: 'manager' },
  };
}
